version: '3.8'

services:
  # Ana Ürün API'si (Beyin)
  main-api:
    build:
      context: ./hukuk-asistan-main
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - scraper-api
    environment:
      - SCRAPER_API_URL=http://scraper-api:8001

  # Scraper API (İşçi)
  scraper-api:
    build:
      context: ./yargitay-scraper-api
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - selenium-hub

  # Selenium Servisleri
  selenium-hub:
    image: selenium/hub:4.11.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome-node:
    image: selenium/node-chrome:4.11.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "7900:7900"  # VNC web interface
    shm_size: '2g'