global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Main API monitoring
  - job_name: 'main-api'
    static_configs:
      - targets: ['main-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Scraper API monitoring  
  - job_name: 'scraper-api'
    static_configs:
      - targets: ['scraper-api:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/nginx_status'

  # Selenium Grid monitoring
  - job_name: 'selenium-hub'
    static_configs:
      - targets: ['selenium-hub:4444']
    metrics_path: '/status'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Alert rules
rule_files:
  - "alert_rules.yml"